# vim:fileencoding=utf-8:foldmethod=marker


#: windows
macos_hide_titlebar yes
hide_window_decorations titlebar-only
# window_margin_width 10 10 10 10 
window_margin_width 0 0 0 0
window_padding_width 10 10 10 10
tab_bar_style fade


#: themes
include ./pink-lavender.conf
# include ./catppuccin/themes/frappe.conf
# include ./rose-pine.conf


#: fonts
font_family      JetBrains Mono NerdFont
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
# font_size 11.0
# force_ltr no
# disable_ligatures never


#: mouse & keys
mouse_hide_wait 3.0
# focus_follows_mouse no
# macos_option_as_alt no


#: background colors. (catpuccin_frappe: 0.7 | pink-lavender: 0.5 | rose-pine: 0.6)
background_opacity 0.5
# background_blur 0
# background_tint 0.0


#: text cursor customization
# cursor #cccccc
# cursor_text_color #111111
# cursor_shape block
# cursor_shape_unfocused hollow
# cursor_beam_thickness 1.5
# cursor_underline_thickness 2.0
# cursor_blink_interval -1
# cursor_stop_blinking_after 15.0
# cursor_trail 0
# cursor_trail 1
# cursor_trail_decay 0.1 0.4
# cursor_trail_start_threshold 2

